source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-partial'
gem 'capybara'
gem 'cucumber'
gem 'cucumber-sinatra'
gem 'rspec'
gem 'rack-flash3'
gem 'database_cleaner'
gem 'bcrypt-ruby'
gem 'dm-postgres-adapter'
gem 'data_mapper'
gem 'chartkick'
gem 'byebug'
gem 'launchy'
